### ISSUE TITLE
Allocate Project Needs Fixing 

### ISSUE THREAD

**Issue by SinghHrmn** [GurpreetSarangal/Project-Allotment-Software#1]
There are couple of things that need fixing in allocate project page

- [x] make sure that we are using client side verification first
- [x] add typing hints for roll numbers
- [x] only show projects which are not allocated for a particular class

**Comment by GurpreetSarangal** [comment]
Hi @SinghHrmn, I just completed all the tasks.  
- login page is now using jQuery validate plugin to validate inputs
- while allocating projects, roll numbers are given typing hints
- And, only those project shown which are available.
